apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  type: NodePort   # use LoadBalancer if you're on AWS, GCP, Azure
  selector:
    app: flask-app
  ports:
  - name: http
    protocol: TCP
    port: 80          # external port (what users access)
    targetPort: 5000  # container port inside Flask app
    nodePort: 30007   # optional; Kubernetes can auto-assign if you remove this

